package main

import "text/template"

func init() {
	tmpl = template.Must(template.New("").Parse(`
package {{.PkgName}}
// Generated by mplex-gen
import "sync"
// See the godoc for mplex-gen for more information on this function.
func multiplex{{.PrintName}}(chs []chan {{.ChType}}) chan {{.ChType}} {
	var wg sync.WaitGroup
	out := make(chan {{.ChType}})
	go func() {
		wg.Wait()
		close(out)
	}()
	wg.Add(len(chs))
	for _, ch := range chs {
		go func() {
			for x := range ch {
				out <- x
			}
			wg.Done()
		}()
	}
	return out
}`))
}
